INSERT INTO Carreras (IdCarrera, Nombre) VALUES (1, "Civil");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (2, "Quimica");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (3, "Industrial");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (4, "Electrica");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (5, "Mecanica");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (6, "Mecanica Electrica");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (7, "Mecanica Industrial");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (9, "Ciencias y Sistemas");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (13, "Electronica");
INSERT INTO Carreras (IdCarrera, Nombre) VALUES (35, "Ambiental");
