INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("JOSE RICARDO", "MORALES PRADO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("WILLIAM SAMUEL", "GUEVARA ORELLANA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MIRNA IVONNE", "ALDANA LARRAZABAL");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("OTTO RENE", "ESCOBAR LEIVA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("GABRIEL ALEJANDRO", "DIAS LOPEZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("OTTO AMILCAR", "RODRIGUEZ ACOSTA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("LUIS FERNANDO", "ESPINO BARRIOS");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ALVARO GIOVANNI", "LONGO MORALES");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("LUIS ALBERTO", "ARIAS");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ILEANA GUISELA", "RALDA RECINOS DE ILLESCAS");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("EVELYN CAROLINA", "MORALES RUIZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("LUDWING FEDERICO", "ALTAN SAC");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("JESÚS ALBERTO", "GUZMÁN");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ALVARO OBRAYAN", "HERNANDEZ GARCIA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("LUIS ALBERTO", "VETTORAZZI ESPANA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MARIO JOSE", "BAUTISTA FUENTES");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MARLON FRANCISCO", "ORELLANA LOPEZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("BYRON RODOLFO", "ZEPEDA AREVALO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MOISES EDUARDO", "VELASQUEZ OLIVA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("HERMAN IGOR", "VELIZ LINARES");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("NEFTALI DE JESUS", "CALDERON MENDEZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MARLON ANTONIO", "PEREZ TURK");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("CLAUDIA LICETH", "ROJAS MORALES");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("JOSE MANUEL", "RUIZ JUAREZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("WILLIAM ESTUARDO", "ESCOBAR ARGUETA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("EDWIN ESTUARDO", "ZAPETA GOMEZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("DAVID ESTUARDO", "MORALES");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("VIRGINIA VICTORIA", "TALA AYERDI");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("FLORIZA FELIPA", "AVILA PESQUERA DE MEDINILLA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("JUAN ALVARO", "DIAZ ARDAVIN");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("OSCAR ALEJANDRO", "PAZ CAMPOS");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MIGUEL ANGEL", "CANCINOS RENDON");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("CESAR AUGUSTO", "FERNANDEZ CACERES");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("BAYRON WOSVELY", "LOPEZ LOPEZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("EDGAR RUBEN", "SABAN RAXON");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ERICK CARLOS ROBERTO", "NAVARRO DELGADO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MANUEL HAROLDO", "CASTILLO REYNA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("KEVIN ABDIEL", "LAJPOP AJPACAJA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("GUIPPSY JEANNIRA", "MENENDEZ PEREZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("JOSE ANIBAL", "SILVA DE LOS ANGELES");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("PEDRO PABLO", "HERNANDEZ RAMIREZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MANUEL FERNANDO", "LOPEZ FERNANDEZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("SERGIO ARNALDO", "MENDEZ AGUILAR");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("CESAR ROLANDO", "BATZ SAQUIMUX");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("EVEREST DARWIN", "MEDINILLA RODRIGUEZ");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("JORGE LUIS", "ALVAREZ MEJIA");
