INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MORALES PRADO", "JOSE RICARDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("GUEVARA ORELLANA", "WILLIAM SAMUEL");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ALDANA LARRAZABAL", "MIRNA IVONNE");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ESCOBAR LEIVA", "OTTO RENE");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("DIAS LOPEZ", "GABRIEL ALEJANDRO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("RODRIGUEZ ACOSTA", "OTTO AMILCAR");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ESPINO BARRIOS", "LUIS FERNANDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("LONGO MORALES", "ALVARO GIOVANNI");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ARIAS", "LUIS ALBERTO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("RALDA RECINOS DE ILLESCAS", "ILEANA GUISELA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MORALES RUIZ", "EVELYN CAROLINA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ALTAN SAC", "LUDWING FEDERICO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("GUZMÁN", "JESÚS ALBERTO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("HERNANDEZ GARCIA", "ALVARO OBRAYAN");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("VETTORAZZI ESPANA", "LUIS ALBERTO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("BAUTISTA FUENTES", "MARIO JOSE");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ORELLANA LOPEZ", "MARLON FRANCISCO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ZEPEDA AREVALO", "BYRON RODOLFO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("VELASQUEZ OLIVA", "MOISES EDUARDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("VELIZ LINARES", "HERMAN IGOR");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("CALDERON MENDEZ", "NEFTALI DE JESUS");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("PEREZ TURK", "MARLON ANTONIO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ROJAS MORALES", "CLAUDIA LICETH");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("RUIZ JUAREZ", "JOSE MANUEL");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ESCOBAR ARGUETA", "WILLIAM ESTUARDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ZAPETA GOMEZ", "EDWIN ESTUARDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MORALES", "DAVID ESTUARDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("TALA AYERDI", "VIRGINIA VICTORIA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("AVILA PESQUERA DE MEDINILLA", "FLORIZA FELIPA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("DIAZ ARDAVIN", "JUAN ALVARO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("PAZ CAMPOS", "OSCAR ALEJANDRO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("CANCINOS RENDON", "MIGUEL ANGEL");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("FERNANDEZ CACERES", "CESAR AUGUSTO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("LOPEZ LOPEZ", "BAYRON WOSVELY");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("SABAN RAXON", "EDGAR RUBEN");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("NAVARRO DELGADO", "ERICK CARLOS ROBERTO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("CASTILLO REYNA", "MANUEL HAROLDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("LAJPOP AJPACAJA", "KEVIN ABDIEL");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MENENDEZ PEREZ", "GUIPPSY JEANNIRA");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("SILVA DE LOS ANGELES", "JOSE ANIBAL");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("HERNANDEZ RAMIREZ", "PEDRO PABLO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("LOPEZ FERNANDEZ", "MANUEL FERNANDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MENDEZ AGUILAR", "SERGIO ARNALDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("BATZ SAQUIMUX", "CESAR ROLANDO");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("MEDINILLA RODRIGUEZ", "EVEREST DARWIN");
INSERT INTO Catedraticos (Nombres, Apellidos) VALUES ("ALVAREZ MEJIA", "JORGE LUIS");
