INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (17, "Social Humanistica 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (101, "Matematica Basica 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (69, "Tecnica Complementaria 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (39, "Deportes 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (348, "Quimica General 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (6, "Idioma Tecnico 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (19, "Social Humanistica 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (103, "Matematica Basica 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (5, "Tecnicas de Estudio y de Investigacion");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (147, "Fisica Basica");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (40, "Deportes 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (8, "Idioma Tecnico 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (795, "Logica de Sistemas");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (960, "Matematica de Computo 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (770, "Introduccion a la Programacion 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (107, "Matematica Intermedia 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (150, "Fisica 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (9, "Idioma Tecnico 3");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (732, "Estadistica 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (796, "Lenguajes Formales y de Programacion");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (962, "Matematica de Computo 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (771, "Introduccion a la Programacion 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (10, "Logica");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (112, "Matematica Intermedia 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (114, "Matematica Intermedia 3");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (152, "Fisica 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (11, "Idioma Tecnico 4");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (2025, "Practica Inicial");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (736, "Analisis Probabilistico");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (777, "Organizacion de Lenguajes y Compiladores 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (964, "Organizacion Computacional");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (772, "Estructura de Datos");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (18, "Filosofia de la Ciencia");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (116, "Matematica Aplicada 3");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (118, "Matematica Aplicada 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (368, "Principios de Metrologia");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (650, "Contabilidad 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (28, "Ecologia");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (722, "Teoria de Sistemas 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (601, "Investigacion de Operaciones 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (14, "Economia");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (781, "Organizacion de Lenguajes y Compiladores 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (778, "Arquitectura de Computadoras y Ensambladores 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (773, "Manejo e Implementacion de Archivos");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (122, "Matematica Aplicada 4");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (120, "Matematica Aplicada 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (200, "Ingenieria Electrica 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (652, "Contabilidad 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (335, "Gestion de Desastres");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (724, "Teoria de Sistemas 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (603, "Investigacion de Operaciones 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (734, "Estadistica 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (271, "Sistemas Operativos 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (779, "Arquitectura de Computadoras y Ensambladores 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (970, "Redes de Computadoras 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (774, "Sistemas de Bases de Datos 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (656, "Administracion de Empresas 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (654, "Contabilidad 3");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (2036, "Practica Intermedia");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (285, "Sistemas Operativos 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (975, "Redes de Computadoras 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (775, "Sistemas de Bases de Datos 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (283, "Analisis y Diseño de Sistemas 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (797, "Seminario de Sistemas 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (700, "Ingenieria Economica 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (729, "Modelacion y Simulacion 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (786, "Sistemas Organizacionales y Gerenciales 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (972, "Inteligencia Artificial 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (966, "Seguridad y Auditorias de Redes");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (785, "Analisis y Diseño de Sistemas 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (788, "Sistemas Aplicados 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (738, "Bases de Datos Avanzadas");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (798, "Seminario de Sistemas 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (288, "Introduccion a la Evaluacion de Impacto Ambiental");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (702, "Ingenieria Economica 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (1, "Etica Profesional");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (2009, "Practica Final");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (787, "Sistemas Organizacionales y Gerenciales 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (790, "Emprendedores de Negocios Informaticos");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (720, "Modelacion y Simulacion 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (968, "Inteligencia Artificial 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (974, "Redes de Nueva Generacion");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (780, "Software Avanzado");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (789, "Sistemas Aplicados 2");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (735, "Auditoria de Proyectos de Software");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (7990, "Seminario de Investigacion EPS");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (710, "Planeamiento");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (706, "Preparacion y Evaluacion de Proyectos 1");
INSERT INTO Cursos (CodigoCurso, Nombre) VALUES (799, "Seminario de Investigacion");
